/**
 * src/diarization/speakerRegistry.js
  * Maps Deepgram speaker indices to named participants.
   * Tracks speaker turns and groups consecutive words into utterances.
    */

    const DEFAULT_SPEAKERS = ['JD', 'AK', 'MR', 'SW'];

    class SpeakerRegistry {
      constructo
          this.speakerMap = new Map(); // speakerIdx -> { speakerId, speakerName }
              this.customNames = new Map();
                }

                  /**
                     * Register a custom name for a speaker index.
                        */
                          registerSpeaker(speakerIdx, speakerId, speakerName) {
                              this.speakerMap.set(speakerIdx, { speakerId, speakerName });
                                  this.customNames.set(speakerIdx, { speakerId, speakerName });
                                    }

                                      /**
                                         * Resolve a speaker index to an ID/name, auto-assigning defaults as needed.
                                            */
                                              resolveSpeaker(speakerIdx) {
                                                  if (!this.speakerMap.has(speakerIdx)) {
                                                        const defaultId = DEFAULT_SPEAKERS[speakerIdx % DEFAULT_SPEAKERS.length];
                                                              this.speakerMap.set(speakerIdx, { speakerId: defaultId, speakerName: defaultId });
                                                                  }
                                                                      return this.speakerMap.get(speakerIdx);
                                                                        }

                                                                          /**
                                                                             * Takes an array of Deepgram word objects (each with .speaker, .word, .start, .end)
                                                                                * and groups them into per-speaker utterances, splitting on speaker changes.
                                                                                   */
                                                                                     diarize(words) {
                                                                                         if (!Array.isArray(words) || words.length === 0) return [];

                                                                                             const utterances = [];
                                                                                                 let currentSpeaker = null;
                                                                                                     let currentWords = [];
                                                                                                         let startTime = 0;
                                                                                                             let endTime = 0;
                                                                                                             
                                                                                                                 for (const word of words) {
                                                                                                                       const speakerIdx = word.speaker ?? 0;
                                                                                                                       
                                                                                                                             if (currentSpeaker === null) {
                                                                                                                                     currentSpeaker = speakerIdx;
                                                                                                                                             startTime = word.start ?? 0;
                                                                                                                                                   }
                                                                                                                                                   
                                                                                                                                                         if (speakerIdx !== currentSpeaker) {
                                                                                                                                                                 // Flush current utterance
                                                                                                                                                                         if (currentWords.length > 0) {
                                                                                                                                                                                   const resolved = this.resolveSpeaker(currentSpeaker);
                                                                                                                                                                                             utterances.push({
                                                                                                                                                                                                         speakerIdx: currentSpeaker,
                                                                                                                                                                                                                     speakerId: resolved.speakerId,
                                                                                                                                                                                                                                 speakerName: resolved.speakerName,
                                                                                                                                                                                                                                             text: currentWords.join(' '),
                                                                                                                                                                                                                                                         startTime,
                                                                                                                                                                                                                                                                     endTime,
                                                                                                                                                                                                                                                                                 duration: Math.round((endTime - startTime) * 100) / 100
                                                                                                                                                                                                                                                                                           });
                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                           // Start new utterance
                                                                                                                                                                                                                                                                                                                   currentSpeaker = speakerIdx;
                                                                                                                                                                                                                                                                                                                           currentWords = [];
                                                                                                                                                                                                                                                                                                                                   startTime = word.start ?? 0;
                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                               currentWords.push(word.punctuated_word || word.word || '');
                                                                                                                                                                                                                                                                                                                                                     endTime = word.end ?? 0;
                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                             // Flush last utterance
                                                                                                                                                                                                                                                                                                                                                                 if (currentWords.length > 0 && currentSpeaker !== null) {
                                                                                                                                                                                                                                                                                                                                                                       const resolved = this.resolveSpeaker(currentSpeaker);
                                                                                                                                                                                                                                                                                                                                                                             utterances.push({
                                                                                                                                                                                                                                                                                                                                                                                     speakerIdx: currentSpeaker,
                                                                                                                                                                                                                                                                                                                                                                                             speakerId: resolved.speakerId,
                                                                                                                                                                                                                                                                                                                                                                                                     speakerName: resolved.speakerName,
                                                                                                                                                                                                                                                                                                                                                                                                             text: currentWords.join(' '),
                                                                                                                                                                                                                                                                                                                                                                                                                     startTime,
                                                                                                                                                                                                                                                                                                                                                                                                                             endTime,
                                                                                                                                                                                                                                                                                                                                                                                                                                     duration: Math.round((endTime - startTime) * 100) / 100
                                                                                                                                                                                                                                                                                                                                                                                                                                           });
                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                   return utterances;
                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                       reset() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                           this.speakerMap.clear();
                                                                                                                                                                                                                                                                                                                                                                                                                                                               // Preserve any custom names across resets
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   for (const [idx, info] of this.customNames.entries()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         this.speakerMap.set(idx, info);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               export const speakerRegistry = new SpeakerRegistry();
