/**
 * src/intelligence/intelligenceProcessor.js
  * AI-powered intelligence extraction from meeting utterances.
   * Uses GPT-4o to identify decisions, action items, and sentiment.
    */
    import { EventEmitter } from 'events';
    import OpenAI from 'openai';

    const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

    const WINDOW_SIZE = 8;        // utterances per processing window
    const WINDOW_OVERLAP = 2;     // utterances carried forward for context

    class IntelligenceProcessor extends EventEmitter {
      constructor() {
          super();
              this.utterances = [];
                  this.windowBuffer = [];
                      this.decisions = [];
                          this.actions = [];
                              this.sentimentHistory = [];
                                  this.windowsProcessed = 0;
                                    }

                                      reset() {
                                          this.utterances = [];
                                              this.windowBuffer = [];
                                                  this.decisions = [];
                                                      this.actions = [];
                                                          this.sentimentHistory = [];
                                                              this.windowsProcessed = 0;
                                                                }

                                                                  async addUtterance(utterance) {
                                                                      this.utterances.push(utterance);
                                                                          this.windowBuffer.push(utterance);

                                                                              if (this.windowBuffer.length >= WINDOW_SIZE) {
                                                                                    const windowToProcess = [...this.windowBuffer];
                                                                                          this.windowBuffer = this.windowBuffer.slice(-WINDOW_OVERLAP);
                                                                                                await this._processWindow(windowToProcess);
                                                                                                    }
                                                                                                      }
                                                                                                      
                                                                                                        async _processWindow(window) {
                                                                                                            const transcript = window
                                                                                                                  .map((u) => `[${u.speakerId || 'Unknown'}]: ${u.text}`)
                                                                                                                        .join('\n');
                                                                                                                        
                                                                                                                            try {
                                                                                                                                  const response = await openai.chat.completions.create({
                                                                                                                                          model: 'gpt-4o',
                                                                                                                                                  temperature: 0.2,
                                                                                                                                                          messages: [
                                                                                                                                                                    {
                                                                                                                                                                                role: 'system',
                                                                                                                                                                                            content: `You are an AI meeting intelligence engine. Analyze the transcript segment and extract:
                                                                                                                                                                                            1. Decisions made (with who decided and rationale)
                                                                                                                                                                                            2. Action items (owner, task, deadline if mentioned, priority)
                                                                                                                                                                                            3. Overall sentiment (positive/neutral/negative) and momentum score 0-100
                                                                                                                                                                                            
                                                                                                                                                                                            Respond ONLY with valid JSON in this exact format:
                                                                                                                                                                                            {
                                                                                                                                                                                              "decisions": [{ "id": "d1", "decision": "...", "decidedBy": "...", "rationale": "...", "confidence": 0.9 }],
                                                                                                                                                                                                "actions": [{ "id": "a1", "owner": "...", "task": "...", "deadline": "...", "priority": "high|medium|low", "dependencies": [], "status": "open" }],
                                                                                                                                                                                                  "sentiment": { "label": "positive|neutral|negative", "meetingMood": "...", "momentumScore": 75 }
                                                                                                                                                                                                  }`
                                                                                                                                                                                                            },
                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                  role: 'user',
                                                                                                                                                                                                                                              content: `Transcript segment:\n${transcript}`
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                            const raw = response.choices[0]?.message?.content || '{}';
                                                                                                                                                                                                                                                                                  const intel = JSON.parse(raw);
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                        if (Array.isArray(intel.decisions)) {
                                                                                                                                                                                                                                                                                                this.decisions.push(...intel.decisions);
                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                            if (Array.isArray(intel.actions)) {
                                                                                                                                                                                                                                                                                                                    this.actions.push(...intel.actions);
                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                if (intel.sentiment) {
                                                                                                                                                                                                                                                                                                                                        this.sentimentHistory.push(intel.sentiment);
                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                    this.windowsProcessed++;
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                          this.emit('intel-update', {
                                                                                                                                                                                                                                                                                                                                                                  decisions: intel.decisions || [],
                                                                                                                                                                                                                                                                                                                                                                          actions: intel.actions || [],
                                                                                                                                                                                                                                                                                                                                                                                  sentiment: intel.sentiment || null,
                                                                                                                                                                                                                                                                                                                                                                                          windowIndex: this.windowsProcessed
                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                          console.error('[INTELLIGENCE] Processing error:', err.message);
                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                  generatePostCallSummary() {
                                                                                                                                                                                                                                                                                                                                                                                                                      const avgMomentum =
                                                                                                                                                                                                                                                                                                                                                                                                                            this.sentimentHistory.length > 0
                                                                                                                                                                                                                                                                                                                                                                                                                                    ? Math.round(
                                                                                                                                                                                                                                                                                                                                                                                                                                                this.sentimentHistory.reduce((sum, s) => sum + (s.momentumScore || 50), 0) /
                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.sentimentHistory.length
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : 50;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const lastMood =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.sentimentHistory.length > 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ? this.sentimentHistory[this.sentimentHistory.length - 1].meetingMood
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          : 'neutral';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    decisions: this.decisions,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          actions: this.actions,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sentiment: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        meetingMood: lastMood,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                momentumScore: avgMomentum
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            totalUtterances: this.utterances.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  windowsProcessed: this.windowsProcessed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export const intelligenceProcessor = new IntelligenceProcessor();
